@baseUrl = http://localhost:8081

### Create Auction Report
POST {{baseUrl}}/report-auction
Content-Type: application/json

{
  "userId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  "auctionId": 101,
  "sellerId": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
  "auctionTitle": "iPhone 15 Pro Max 256GB",
  "auctionDescription": "Vendo iPhone 15 Pro Max em ótimo estado, sem arranhões.",
  "reportReason": "Produto suspeito de ser falsificado.",
  "auctionThumb": "https://cdn.example.com/auctions/101/thumb.jpg"
}


### Message Report
POST {{baseUrl}}/report-message
Content-Type: application/json

{
  "userId": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  "auctionId": 101,
  "sellerId": "b2c3d4e5-f6a7-8901-bcde-f12345678901",
  "messageId": 55,
  "message": "Pode me passar seu pix para eu pagar fora da plataforma?",
  "reportReason": "Vendedor tentando realizar pagamento fora da plataforma."
}
