services:
  report-service:
    container_name: report-service
    image: pedrovncs/report-service:latest
    restart: always
    ports:
      - "${REPORT_SERVICE_PORT:-8081}:8081"
    environment:
      REPORT_SERVICE_PORT: ${REPORT_SERVICE_PORT:-8081}
      SPRING_DATASOURCE_URL: "${SPRING_DATASOURCE_URL:-jdbc:postgresql://report-service-postgres:5432/report}"
      REPORT_SERVICE_DB_USER: ${REPORT_SERVICE_DB_USER:-report}
      REPORT_SERVICE_DB_PASSWORD: ${REPORT_SERVICE_DB_PASSWORD:-report}
      KAFKA_SERVERS: "${KAFKA_SERVERS:-localhost:9092}"
    networks:
      - leilao-network
    depends_on:
      report-service-postgres:
        condition: service_healthy

  report-service-postgres:
    image: postgres:15-alpine
    container_name: report-service-postgres
    ports:
      - "${REPORT_SERVICE_DB_PORT:-5434}:5432"
    environment:
      POSTGRES_DB: report
      POSTGRES_USER: ${REPORT_SERVICE_DB_USER:-report}
      POSTGRES_PASSWORD: ${REPORT_SERVICE_DB_PASSWORD:-report}
    volumes:
      - report-service-postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro
    networks:
      - leilao-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  leilao-network:
    external: true

volumes:
  report-service-postgres-data:
