services:
  report-service-postgres:
    image: postgres:15-alpine
    container_name: report-service-postgres
    ports:
      - "${REPORT_SERVICE_DB_PORT:-5434}:5432"
    environment:
      POSTGRES_DB: ${REPORT_SERVICE_DB_NAME:-report}
      POSTGRES_USER: ${REPORT_SERVICE_DB_USER:-report}
      POSTGRES_PASSWORD: ${REPORT_SERVICE_DB_PASSWORD:-report}
    volumes:
      - report-service-postgres-data:/var/lib/postgresql/data

volumes:
  report-service-postgres-data:
