services:
  postgres:
    image: postgres:15-alpine
    container_name: report-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: report
      POSTGRES_USER: report
      POSTGRES_PASSWORD: report
    volumes:
      - report-postgres-data:/var/lib/postgresql/data

volumes:
  report-postgres-data: