server:
  port: 8081

spring:
  application:
    name: report
  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5434/report
    username: report
    password: report
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: report-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.add.type.headers: false
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


app:
  kafka-topics:
    reports:
      auction-pending-review: "reports.auction.pending.review"
      qa-pending-review: "reports.qa.pending.review"